total_steps = 1000000

[model]
name = "14M"
compile = true

[data]
name = "allenai/c4"
micro_batch_size = 16
batch_size = 256
seq_len = 2048

[lr_scheduler]
type = "linear"
warmup_steps = 20
decay_steps = 0